# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      # - run: npm test

      - add_ssh_keys:
          fingerprints:
            - "8e:24:63:c7:5a:5a:c8:b4:ab:54:8c:9c:34:b1:f9:61"
            - "d9:78:1d:84:33:c7:85:5a:9e:ce:2e:c5:1e:00:1c:65"
      - run: 
          name: deploy over SCP
          command: scp -r * ubuntu@ec2-18-191-126-205.us-east-2.compute.amazonaws.com:circle-ci-test
  
  # deploy:
  #   machine:
  #     enabled: true

  #   steps: 
  #     - add_ssh_keys:
  #         fingerprints:
  #           - "8e:24:63:c7:5a:5a:c8:b4:ab:54:8c:9c:34:b1:f9:61"
  #     - run: 
  #         name: deploy over SCP
  #         command: scp -r circle-ci-test/* ubuntu@ec2-18-191-126-205.us-east-2.compute.amazonaws.com:circle-ci-test
      # - run:
      #     name: Deploy over SSH
      #     command: ssh ubuntu@ec2-18-191-126-205.us-east-2.compute.amazonaws.com
      # - run:
      #     name: clone
      #     command: cd circle-ci-test && git pull origin master
      # - run:
      #     name: exit SSH
      #     command: exit 

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #       - build